### PR TITLE
first package version

### PR DESCRIPTION
**Pull request by mdsteiner**
Note that I now pushed the package so all the tutorials and stuff is deleted to have a clean package. I still have the tutorials of course so we might add them to another repository or so.

### CODE REVIEW

**Comment by ndphillips** [comment]
Great! Is there a reason why you removed the tutorials? Do you need to 'clean them up' before including them?

**Comment by mdsteiner** [comment]
No now they are ready, here's the link to the "front page" from which you can then access the specific tutorials.
http://rpubs.com/msteiner/ShinyPsych_Guide
I didn't include them, because then everyone who downloads the package would also have all the markdown files in the package. but if you'd like I can add them in the inst folder...

**Comment by mdsteiner** [comment]
it would of course be an advantage if they were in the package, because then you could also make changes (I think it would make sense at some point for you to go through them to check my englisch and so on), but I could also push them to another repo, whatever you prefer...

**Comment by ndphillips** [comment]
I think they should definitely be included in the package as vignettes. That's what I do with my packages (see https://github.com/ndphillips/FFTrees/tree/master/vignettes).

If you haven't seen this already, Wickham has a guide on creating vignettes here: 
http://r-pkgs.had.co.nz/vignettes.html. As vignettes are just markdown documents, you should very easily be able to put what you've already created in the appropriate format. 

If you haven't already, I would also recommend creating an overall package guide like this one (https://github.com/ndphillips/FFTrees/blob/master/vignettes/guide.Rmd), with links to more specific vignettes. (Now I of course see you've already done this!)

Later on, you can also create a package startup message like the one in yarrr (https://github.com/ndphillips/FFTrees/blob/master/R/zzz.R) that tells the user how to open the main guide.

**Comment by mdsteiner** [comment]
How is it that on the github page of the FFTrees package, you don't have a doc folder containing the html vignettes but in the downloaded FFTrees version I have it? The thing is, that for vignettes() to work I think the vignettes must be built, so I could run built_vignettes but then the package becomes even larger than it already is.

**Comment by ndphillips** [comment]
When you install a package from github, you can automatically build the vignettes (on the client side) by including the argument `build_vignettes = TRUE`. e.g.; `devtools::install_github('ndphillips/FFTrees', build_vignettes = TRUE)` Couldn't we require that the user includes this argument?

**Comment by mdsteiner** [comment]
ah yes I will include that.

**Comment by mdsteiner** [comment]
ok startup info is included.

**Pull request merged**
